SHOW SCHEMAS IN DATABASE ELT_DEV;
SHOW TABLES IN SCHEMA ELT_DEV.BRONZE;
SHOW DYNAMIC TABLES IN SCHEMA ELT_DEV.SILVER;
SHOW DYNAMIC TABLES IN SCHEMA ELT_DEV.GOLD;
SHOW WAREHOUSES;

SELECT
    CURRENT_DATABASE(),
    CURRENT_SCHEMA(),
    CURRENT_WAREHOUSE(),
    CURRENT_ROLE(),
    CURRENT_USER();

SELECT extracted_at, payload:count AS n
FROM ELT_DEV.BRONZE.CAD_RAW;

SELECT COUNT(*) AS n_silver 
FROM ELT_DEV.SILVER.CAD;

SELECT * 
FROM ELT_DEV.GOLD.CAD_KPI;

SELECT COUNT(*) AS n_flybys 
FROM ELT_DEV.GOLD.CAD_FLYBYS;

SELECT * 
FROM ELT_DEV.GOLD.CAD_BY_DAY 
ORDER BY approach_day;

SELECT warehouse_name, user_name, query_text, start_time
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE user_name = 'CAD_LOADER'
ORDER BY start_time DESC
LIMIT 20;

-- GRANT USAGE ON WAREHOUSE DASHBOARD_WH TO USER CAD_LOADER;

-- ALTER DYNAMIC TABLE ELT_DEV.SILVER.CAD REFRESH;
-- ALTER DYNAMIC TABLE ELT_DEV.GOLD.CAD_FLYBYS REFRESH;
-- ALTER DYNAMIC TABLE ELT_DEV.GOLD.CAD_KPI REFRESH;
-- ALTER DYNAMIC TABLE ELT_DEV.GOLD.CAD_BY_DAY REFRESH;
