--Do not execute as a whole!
--Archive: Snowflake Worksheet
CREATE DATABASE IF NOT EXISTS ELT_DEV;
CREATE SCHEMA IF NOT EXISTS ELT_DEV.BRONZE;
CREATE SCHEMA IF NOT EXISTS ELT_DEV.SILVER;
CREATE SCHEMA IF NOT EXISTS ELT_DEV.GOLD;

USE DATABASE ELT_DEV;
USE SCHEMA BRONZE;

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();
SHOW SCHEMAS IN DATABASE ELT_DEV;

USE SCHEMA ELT_DEV.BRONZE;

CREATE OR REPLACE TABLE CAD_RAW (
    extracted_at STRING,
    payload VARIANT
);

INSERT INTO CAD_RAW
SELECT 
    'manual-sample',
    PARSE_JSON('
    {
        "count": 2,
        "fields": ["des", "orbit_id", "jd", "cd", "dist", "dist_min", "dist_max", "v_rel"],
        "data": [
            ["2026 QB2","1","2461284.6","2026-Sep-01 02:53","0.0132","0.0127","0.0137","13.69"],
            ["2025 CL3","5","2461284.7","2026-Sep-01 04:24","0.0245","0.0009","0.0490","13.54"]
        ]
    }
    ');

SELECT extracted_at, payload:count AS cnt FROM CAD_RAW;

CREATE OR REPLACE TABLE ELT_DEV.SILVER.CAD AS
SELECT 
    f.value[0]::STRING AS designation,
    f.value[3]::STRING AS approach_at, 
    f.value[4]::FLOAT AS dist_au,
    f.value[7]::FLOAT AS v_rel_kms
FROM ELT_DEV.BRONZE.CAD_RAW,
LATERAL FLATTEN(input => payload:data) f;

SELECT COUNT(*) FROM ELT_DEV.SILVER.CAD;
SELECT * FROM ELT_DEV.SILVER.CAD;

CREATE OR REPLACE TABLE ELT_DEV.GOLD.CAD_CLOSEST AS 
SELECT designation, approach_at, dist_au, v_rel_kms
FROM ELT_DEV.SILVER.CAD
ORDER BY dist_au ASC;

SELECT * FROM ELT_DEV.GOLD.CAD_CLOSEST;

--SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();
--SELECT CURRENT_ACCOUNT();
--SELECT CURRENT_USER();
--SELECT CURRENT_ROLE();
--SELECT CURRENT_WAREHOUSE();
--SELECT CURRENT_DATABASE();
--SELECT CURRENT_SCHEMA();

--USE ROLE ACCOUNTADMIN;

--CREATE USER IF NOT EXISTS CAD_LOADER
--    PASSWORD = ...
--    LOGIN_NAME = 'CAD_LOADER'
--    DEFAULT_ROLE = ACCOUNTADMIN
--    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
--    MUST_CHANGE_PASSWORD = FALSE;

--GRANT ROLE ACCOUNTADMIN TO USER CAD_LOADER;


SELECT extracted_at FROM ELT_DEV.BRONZE.CAD_RAW;
SELECT payload:count AS anzahl FROM ELT_DEV.BRONZE.CAD_RAW;
SELECT COUNT(*) FROM ELT_DEV.BRONZE.CAD_RAW;

--How close in km?
CREATE OR REPLACE TABLE ELT_DEV.GOLD.CAD_FLYBYS AS
SELECT 
    designation,
    approach_at,
    dist_au,
    ROUND(dist_au * 149597870.7, 0) AS dist_km,--149597870.7 km / 1 AU
    v_rel_kms,
    CASE 
        WHEN dist_au < 0.01 THEN 'sehr nah'
        WHEN dist_au < 0.03 THEN 'nah'
        ELSE 'moderat'
    END AS closeness
FROM ELT_DEV.SILVER.CAD;

SELECT * FROM ELT_DEV.GOLD.CAD_FLYBYS ORDER BY dist_au ASC;

--How many approaches? closest distance, max. speed
CREATE OR REPLACE TABLE ELT_DEV.GOLD.CAD_KPI AS 
SELECT
    COUNT(*) AS n_approaches,
    MIN(dist_au) AS min_dist_au,
    ROUND(MIN(dist_au) * 149597870.7, 0) AS min_dist_km,
    MAX(v_rel_kms) AS max_speed_kms
FROM ELT_DEV.SILVER.CAD;

SELECT * FROM ELT_DEV.GOLD.CAD_KPI;

--Approaches per day
CREATE OR REPLACE TABLE ELT_DEV.GOLD.CAD_BY_DAY AS
SELECT 
    TO_DATE(TO_TIMESTAMP_NTZ(approach_at, 'YYYY-MON-DD HH24:MI')) AS approach_day,
    COUNT(*) AS n_approaches,
    MIN(dist_au) AS min_dist_au
FROM ELT_DEV.SILVER.CAD
GROUP BY 1
ORDER BY 1;

SELECT * FROM ELT_DEV.GOLD.CAD_BY_DAY;


--Replace Silver->Gold with Dynamic Tables for orchestration
DROP TABLE IF EXISTS ELT_DEV.GOLD.CAD_BY_DAY;
DROP TABLE IF EXISTS ELT_DEV.GOLD.CAD_KPI;
DROP TABLE IF EXISTS ELT_DEV.GOLD.CAD_FLYBYS;
DROP TABLE IF EXISTS ELT_DEV.GOLD.CAD_CLOSEST;
DROP TABLE IF EXISTS ELT_DEV.SILVER.CAD;

CREATE OR REPLACE DYNAMIC TABLE ELT_DEV.SILVER.CAD
    TARGET_LAG = '3 days'
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
AS 
SELECT
    f.value[0]::STRING AS designation,
    f.value[3]::STRING AS approach_at,
    f.value[4]::FLOAT AS dist_au,
    f.value[7]::FLOAT AS v_rel_kms
FROM ELT_DEV.BRONZE.CAD_RAW,
LATERAL FLATTEN(input => payload:data) f;

CREATE OR REPLACE DYNAMIC TABLE ELT_DEV.GOLD.CAD_FLYBYS
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
AS 
SELECT 
    designation,
    approach_at,
    dist_au,
    ROUND(dist_au * 149597870.7, 0) AS dist_km,
    v_rel_kms,
    CASE
        WHEN dist_au < 0.01 THEN 'very close'
        WHEN dist_au < 0.03 THEN 'close'
        ELSE 'moderate'
    END AS closeness
FROM ELT_DEV.SILVER.CAD;

CREATE OR REPLACE DYNAMIC TABLE ELT_DEV.GOLD.CAD_KPI
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
AS 
SELECT
    COUNT(*) AS n_approaches,
    MIN(dist_au) AS min_dist_au,
    ROUND(MIN(dist_au) * 149597870.7, 0) AS min_dist_km,
    MAX(v_rel_kms) AS max_speed_kms
FROM ELT_DEV.SILVER.CAD;

CREATE OR REPLACE DYNAMIC TABLE ELT_DEV.GOLD.CAD_BY_DAY
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
AS 
SELECT 
    TO_DATE(TO_TIMESTAMP_NTZ(approach_at, 'YYYY-MON-DD HH24:MI')) AS approach_day,
    COUNT(*) AS n_approaches,
    MIN(dist_au) AS min_dist_au
FROM ELT_DEV.SILVER.CAD
GROUP BY 1;

ALTER DYNAMIC TABLE ELT_DEV.SILVER.CAD REFRESH;

SELECT COUNT(*) FROM ELT_DEV.SILVER.CAD;
SELECT * FROM ELT_DEV.GOLD.CAD_KPI;

CREATE WAREHOUSE IF NOT EXISTS DASHBOARD_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Streamlit Gold reads only';

-- GRANT USAGE ON WAREHOUSE DASHBOARD_WH TO USER CAD_LOADER;

SHOW WAREHOUSES;

SELECT warehouse_name, user_name, query_text, start_time
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE warehouse_name = 'SNOWFLAKE_LEARNING_WH'
ORDER BY start_time DESC
LIMIT 20;

SHOW DYNAMIC TABLES IN SCHEMA ELT_DEV.SILVER;
SHOW DYNAMIC TABLES IN SCHEMA ELT_DEV.GOLD;

SELECT extracted_at, payload:count AS n
FROM ELT_DEV.BRONZE.CAD_RAW;

ALTER DYNAMIC TABLE ELT_DEV.SILVER.CAD REFRESH;
ALTER DYNAMIC TABLE ELT_DEV.GOLD.CAD_FLYBYS REFRESH;
ALTER DYNAMIC TABLE ELT_DEV.GOLD.CAD_KPI REFRESH;
ALTER DYNAMIC TABLE ELT_DEV.GOLD.CAD_BY_DAY REFRESH;
